# Generated by Django 3.0 on 2019-12-10 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('words', models.TextField(max_length=200, null=True)),
                ('rsvp', models.BooleanField(default=True)),
            ],
        ),
    ]
