# Generated by Django 2.1.1 on 2019-12-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmas', '0002_comment_hostnamechoice_hostpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpost',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
