# Generated by Django 2.1.1 on 2019-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmas', '0003_auto_20191210_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostpost',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
